### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by huangfeng95** [Doch88/rpg_eklt_multithreading#1]
Hi, thank you for this project.

I found that compared with the uzh-rpg's project, your project doesn't seem to have the visualization of feature_tracks. Does the project support visualization?

**Comment by Doch88** [comment]
Hello :)
Sorry, I only noticed the issue now.
No, the code does not support the "real-time" visualization. With the current code, the visualization can only be done using the generated track file with the visualize.py script from this repository: [https://github.com/uzh-rpg/rpg_feature_tracking_analysis](https://github.com/uzh-rpg/rpg_feature_tracking_analysis)

Since the changes affected the main loop, the real-time visualization had to be heavily changed accordingly, which was not the project's scope. 
With this university project, we only wanted to prove that the code could be highly optimized using multithreading so that this project can be considered whenever developing new algorithms for event-based tracking of features.
